Dictionary/config/routes.rb
Dictionary::Application.routes.draw do

  get "login", :to => "sessions#new"
  get "words/new"
  get "sessions/create"
  get "sessions/destroy"
  get "sessions/profile"
  get "words/inc_votes"
  get "words/dec_votes"
  get "words/decreace_votes"
  get "index", :to => "home#index"
  get "random", :to => "home#random"
  resources :registrations
  resources :home, :only => [:index]
  resources :words
  resources :sessions, :only => [:new, :create, :destroy]  

end

Dictionary/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
      if params[:letter]
        @src = Word.search_by_prefix(params[:letter]).order('word ASC').to_a
      end

      if params[:usr]
        @search = params[:usr]
        @src = Word.where(author: @search).order('factor DESC')
        if @src.empty?
          $error = "No words from that user. Sorry."
          redirect_to(:controller => 'home', :action => 'index')
        end
      end
      if params[:lang]
        @search = params[:lang]
        @src = Word.where(language: @search).order('factor DESC')
        if @src.empty?
          $error = "No words added with that language."
          redirect_to(:controller => 'home', :action => 'index')
        end
      end
      if params[:src]
        @search = params[:src]
        @src = Word.where(word: @search).order('factor DESC')
        if @src.empty?
          $error = "Word doesn't exist."
          redirect_to(:controller => 'home', :action => 'index')
        end
      end
  end

  def random
    @rand = Word.limit(1).order("RAND()").take
  end
end

Dictionary/app/helpers/home_helper.rb
module HomeHelper
end

Dictionary/app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en"><head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="http://getbootstrap.com/docs-assets/ico/favicon.png">

    <link href="app/assets/stylesheets/bootstrap.css" rel="stylesheet">
    <link href="app/assets/stylesheets/custom.css" rel="stylesheet">
    
    
  </head>

  <body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Dictionary</a>
        </div>
        <div class="navbar-collapse collapse">
          <form class="navbar-form navbar-right" role="form">
            <% if session[:reg_id].nil? %>
            <a href="/login" role="button" class="btn btn-primary">Sign In</a> 
            <a href="/registrations/new" role="button" class="btn btn-primary">Register</a>
            <% end %>
            <% if session[:reg_id]%>
              <p class="navbar-brand">Wellcome, <%=session[:reg_username]%></p>
              <a href="/sessions/destroy" role="button" class="btn btn-primary">Log Out</a>
              <a href="/sessions/profile" role="button" class="btn btn-primary">Profile</a>
            <%end%>
          </form>
        </div>
      </div>
    </div>

    
    <div class="jumbotron ">
      <%if $error%>
        <%if $error == "Word doesn't exist." && session[:reg_id]%>
          <div class="error_container">
            <p class="error"><%= $error %><a href="/words/new"> Add it?</a></p>
            <% $error= nil %>
          </div>
        <% end %>
        <%if $error == "Word doesn't exist." && !session[:reg_id]%>
          <% $error= "No such word." %>
          <div class="error_container">
            <p class="error"><%= $error %><a href="/registrations/new"> Register to add it?</a></p>
            <% $error= nil %>
          </div>
        <% end %>
        <%if $error%>
          <div class="error_container">
            <p class="error"><%= $error %></p>
          </div>
        <%end%>
      <% end %>
      <% $error= nil %>
    </div>

    
      <div class="span2" >
        <ul class="nav nav-tabs nav-stacked">
            <li class="active">
                <a href="home">Home</a>
            </li>
            <li>
              <a href="/random">random</a>
            </li>
            <%("a".."z").each do |letter|%>
            <li>
              <a href="/index?letter=<%= letter %>"><%= letter %></a>
            </li>
            <% end %>
        </ul>
      </div>
        
        <div class="span8">
          <% if @src
            @author = Registration.where(id: session[:reg_id]).take
              if @author
                @author_username = @author.username
              end

              @src.each do |word|
                
              @up = (word.votes.to_f / (word.votes+word.downvotes))*100
              @down = (word.downvotes.to_f / (word.votes+word.downvotes))*100
                  
              @desc = word.description.split(/(\b[^\s]+\b)/)
          %>
          
            <div id="<%= word.id %>" class="span7" style="border:solid; margin-top:5px;border: 1px solid #DDDDDD;border-top-right-radius:3em;">

            <div class="span6" style="margin-top:20px;">
             <div class="span3"><a class="wordlink" href="/index?src=<%=word.word%>"><%=word.word%></a></div> 
            </div>
            
            <div class="span6">
              <hr>
                <p>
                  <% @desc.each do |desc|%>
                    <a href="/index?src=<%= desc %>"><%= desc %></a>
                  <% end %>
                </p>
            </div>

            <div name="<%=word.id%>" id="<%= session[:reg_id]%>" class="cv span6">
              <hr>
              <div class="progress">
                <div class="progress-bar progress-bar-success" style="width:<%= @up %>%">
                  
                  <p><%= word.votes %></p>
                </div>
                <div class="progress-bar progress-bar-danger" style="width:<%= @down %>%">
                  
                  <p><%= word.downvotes%></p>
                </div>
              </div>
              <% if session[:reg_id]%>
                    
                <%if !Vote.where(user_id: session[:reg_id],word_id: word.id).exists?%>
                  <button id="u<%= word.id %>" class="up btn btn-success">+</button>
                  <button id="d<%= word.id %>" class="down btn btn-danger">-</button>              
                <%end%>
                <%if Vote.where(user_id: session[:reg_id],word_id: word.id).exists? %>
                    <div id="<%= word.id %>" class="cv" name="<%=session[:reg_id]%>">
                      <button id="<%= word.id %>c" class="btn btn-primary">Change Vote</button>
                    </div>  
                <%end%>
              <%end%>
             
              
            </div>

            <div class="span2">
              <p>by <%= word.author %></p>
              
            </div>
            <% if @author_username == word.author %>
            <div class="span1">
              <%= link_to "Edit", edit_word_path(word), class: "btn btn-primary", name: "ed"%>
            </div>
            <div class="span1" name="ed">
              <%= link_to "Delete", word, :confirm => "Are you sure?", :method => :delete, class: "btn btn-primary", name: "ed"%>
            </div>
            <% end %>
            </div>

            <% end %>
        <% end %>
        </div>
        
  <% if session[:reg_id]%>
    <div class="span2">
      <a href="/words/new" class="btn btn-primary">Add a word</a>
    </div>
  <% end %>
  <% if !session[:reg_id] %>
    <div class="span2"></div>
  <% end %>
    <form action="/index" method="get">
    <div class="span3">
      <input id="src" name="src" type="text" style="height:32px" placeholder="search for a word">
    </div>
     <button class="btn btn-lg btn-primary btn-block" style="width:100px">Search</button>
    </form>
    <form action="/index" method="get">
    <%if @src%>
      <div class="span2"></div>
    <% end %>
    <% if !@src %>
      <div class="span10"></div>
    <%end%>
     

    <div class="span3">
      <input id="usr" name="usr" type="text" style="height:32px" placeholder="search words by user">
    </div>
     <button class="btn btn-lg btn-primary btn-block" style="width:100px">Search</button>
    </form>
    <form action="/index" method="get">
    <%if @src%>
      <div class="span2"></div>
    <% end %>
    <% if !@src%>
      <div class="span10"></div>
    <%end%>
    <div class="span3">
      <input id="lang" name="lang" type="text" style="height:32px" placeholder="search words by language">
    </div>
     <button class="btn btn-lg btn-primary btn-block" style="width:100px">Search</button>
    </form>
    <script type="text/javascript" src="assets/javascript/bootstrap.js"/>
    <script type="text/javascript" src="assets/javascript/votes.js"/>
    <script type="text/javascript" src="assets/javascript/changevotes.js"/>
    <script src="http://code.jquery.com/ui/1.9.2/jquery-ui.js"/>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"/> 
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"/>
  </body>
</html>

Dictionary/app/views/home/random.html.erb
<!DOCTYPE html>
<html lang="en"><head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="http://getbootstrap.com/docs-assets/ico/favicon.png">

    <link href="app/assets/stylesheets/bootstrap.css" rel="stylesheet">
    <link href="app/assets/stylesheets/custom.css" rel="stylesheet">
    
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Dictionary</a>
        </div>
        <div class="navbar-collapse collapse">
          <form class="navbar-form navbar-right" role="form">
            <% if session[:reg_id].nil? %>
            <a href="/sessions/new" role="button" class="btn btn-primary">Sign In</a> 
            <a href="/registrations/new" role="button" class="btn btn-primary">Register</a>
            <% end %>
            <% if session[:reg_id]%>
              <p class="navbar-brand">Wellcome, <%=session[:reg_username]%></p>
              <a href="/sessions/destroy" role="button" class="btn btn-primary">Log Out</a>
            <%end%>
          </form>
        </div>
      </div>
    </div>

    
    <div class="jumbotron">
    </div>

    
      <div class="span2" >
        <ul class="nav nav-tabs nav-stacked">
            <li class="active">
                <a href="index">Home</a>
            </li>
            <li>
              <a href="/random">random</a>
            </li>
            <%("a".."z").each do |letter|%>
            <li>
              <a href="/index?letter=<%= letter %>"><%= letter %></a>
            </li>
            <% end %>
        </ul>
      </div>
        <%  @desc = @rand.description.split(/ /)
            @author = Registration.where(id: session[:reg_id]).take
            if @author

                @author_username = @author.username
              end
            if @rand.votes == 0
                  @up = 0
                else
                  if @rand.downvotes == 0
                    @down = 0
                  else
                    @up = (@rand.votes.to_f / (@rand.votes+@rand.downvotes))*100
                    @down = (@rand.downvotes.to_f / (@rand.votes+@rand.downvotes))*100
                  end
                end

         %>
        <div class="span8">
           <div id="<%= @rand.id %>" class="span7" style="border:solid; margin-top:5px;border: 1px solid #DDDDDD;border-top-right-radius:3em;">

            <div class="span6" style="margin-top:20px;">
             <div class="span3"><a class="wordlink" href="/index?src=<%=@rand.word%>" ><%=@rand.word%></a></div> 
            </div>
              <div class="span6">
                <hr>
                <p>
                  <% @desc.each do |desc|%>
                    <a href="/index?src=<%= desc %>"><%= desc %></a>
                  <% end %>
                </p>
            </div>
            <div class="span6">
              <hr>
              <div class="progress">
                <div class="progress-bar progress-bar-success" style="width:<%= @up %>%">
                  
                  <p><%= @rand.votes %></p>
                </div>
                <div class="progress-bar progress-bar-danger" style="width:<%= @down %>%">
                  
                  <p><%= @rand.downvotes%></p>
                </div>
              </div>
              <% if session[:reg_id]%>
                    
                <%if !Vote.where(user_id: session[:reg_id],word_id: @rand.id).exists?%>
                  <button id="u<%= @rand.id %>" class="up btn btn-success">+</button>
                  <button id="d<%= @rand.id %>" class="down btn btn-danger">-</button>              
                <%end%>
                <%if Vote.where(user_id: session[:reg_id],word_id: @rand.id).exists? %>
                    <div id="<%= @rand.id %>" class="cv" name="<%=session[:reg_id]%>">
                      <button id="<%= @rand.id %>c" class="btn btn-primary">Change Vote</button>
                    </div>  
                <%end%>
              <%end%>
            </div>
            <div class="span2">
              <p>by <%= @rand.author %></p>
            </div>
            <% if @author_username == @rand.author %>
            <div class="span1">
              <%= link_to "Edit", edit_word_path(@rand), class: "btn btn-primary", name: "ed"%>
            </div>
            <div class="span1" name="ed">
              <%= link_to "Delete", @rand, :confirm => "Are you sure?", :method => :delete, class: "btn btn-primary", name: "ed"%>
            </div>  
            <% end %>
          </div>
        </div>
        
  <% if session[:reg_id]%>
    <div class="span2">
      <a href="/words/new" class="btn btn-primary">Add a word</a>
    </div>
  <% end %>
  <% if !session[:reg_id]%>
    <div class="span2"></div>
  <% end %>
    <form action="/index" method="get">
    <div class="span3">
      <input id="src" name="src" type="text" style="height:32px" placeholder="search for a word">
    </div>
     <button class="btn btn-lg btn-primary btn-block" style="width:100px">Search</button>
    </form>
    <div class="span2"></div>
    <form action="/index" method="get">
    <div class="span3">
      <input id="usr" name="usr" type="text" style="height:32px" placeholder="search words by user">
    </div>
     <button class="btn btn-lg btn-primary btn-block" style="width:100px">Search</button>
    </form>
    <form action="/index" method="get">
    <div class="span2"></div>
    <div class="span3">
      <input id="lang" name="lang" type="text" style="height:32px" placeholder="search words by language">
    </div>
     <button class="btn btn-lg btn-primary btn-block" style="width:100px">Search</button>
    </form>
    <script type="text/javascript" src="assets/javascript/bootstrap.js"/>
    <script src="http://code.jquery.com/ui/1.9.2/jquery-ui.js"/>
     <script type="text/javascript" src="assets/javascript/votes.js"/>
    <script type="text/javascript" src="assets/javascript/changevotes.js"/>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"/>
    <script type="text/javascript" src="assets/javascript/votes.js"></script>
  </body>
</html>

Dictionary/app/views/home/show.html.erb
<!DOCTYPE html>
<html lang="en"><head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="http://getbootstrap.com/docs-assets/ico/favicon.png">

    <title>Home</title>

  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Dictionary</a>
        </div>
        <div class="navbar-collapse collapse">
          <form class="navbar-form navbar-right" role="form">
            <div class="form-group">
              <input placeholder="Username" class="form-control" type="text">
            </div>
            <div class="form-group">
              <input placeholder="Password" class="form-control" type="password">
            </div>
            <button type="submit" class="btn btn-success">Sign in</button>
            <a href="/registrations/new" role="button" class="btn">Register</a>
          </form>
        </div><!--/.navbar-collapse -->
      </div>
    </div>

    <script src="Jumbotron%20Template%20for%20Bootstrap_files/jquery-1.js"></script>
    <script src="Jumbotron%20Template%20for%20Bootstrap_files/bootstrap.js"></script>
  

</body></html>